application: sinmetal-gae-pullqueue-gce
version: 20150730a
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /googleed0eded6dfbf426c.html
  static_files: googleed0eded6dfbf426c.html
  upload: googleed0eded6dfbf426c.html
- url: /.*
  script: _go_app
